"""Fixture group 'documents' (spec §16.1). Owned by workstream (b): documents and e-mail.

DOC, DOCX, RTF, ODT, XLS and PPT are generated by LibreOffice at fixture time (from HTML, or
from a small flat-ODF presentation for PPT). Plus the hardening cases:

- damaged.doc       OLE signature followed by garbage: a corrupt file inside a batch (R-12)
- empty.doc         0 bytes
- secret.doc        password-protected Word 97 (encrypted by LibreOffice)     -> plan time
- secret.odt        password-protected ODF                                     -> plan time
- secret.xlsx       password-protected OOXML (OLE EncryptedPackage)            -> LibreOffice fails
- velvet.xls        Excel's default password "VelvetSweatshop": opens without one -> OK
- web-export.xls    HTML saved with an .xls extension (common web-app export)
All content is synthetic.
"""

from __future__ import annotations

import os
import random
import shutil
from pathlib import Path

from .common import write_bytes, write_text

HTML_DOC = """<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title></head><body>
<h1>{title}</h1>
<p>This is a synthetic test document generated for Baleen. It contains <b>bold</b>, <i>italic</i>
and plain text, a short list and a table.</p>
<ul><li>First item</li><li>Second item</li></ul>
<table border="1"><tr><th>Year</th><th>Event</th></tr><tr><td>2003</td><td>Opening</td></tr>
<tr><td>2004</td><td>Tour</td></tr></table>
<p>訪談記錄 — 中文段落，用於字型替代測試 (DR-15).</p>
</body></html>
"""

HTML_TABLE = """<!DOCTYPE html><html><head><meta charset="utf-8"></head><body><table>
<tr><td>Item</td><td>Amount</td></tr><tr><td>Paper</td><td>120</td></tr><tr><td>Ink</td><td>45</td></tr>
<tr><td>Total</td><td>165</td></tr></table></body></html>
"""

FODP = """<?xml version="1.0" encoding="UTF-8"?>
<office:document xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
 xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
 xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
 xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
 xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
 xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
 xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0"
 office:version="1.2" office:mimetype="application/vnd.oasis.opendocument.presentation">
 <office:automatic-styles>
  <style:page-layout style:name="PM1"><style:page-layout-properties fo:page-width="28cm" fo:page-height="21cm"
   style:print-orientation="landscape"/></style:page-layout>
 </office:automatic-styles>
 <office:master-styles>
  <style:master-page style:name="Default" style:page-layout-name="PM1"/>
 </office:master-styles>
 <office:body><office:presentation>
  <draw:page draw:name="Slide 1" draw:master-page-name="Default">
   <draw:frame svg:x="2cm" svg:y="2cm" svg:width="24cm" svg:height="3cm"><draw:text-box>
    <text:p>Synthetic presentation for Baleen</text:p></draw:text-box></draw:frame>
   <draw:frame svg:x="2cm" svg:y="6cm" svg:width="24cm" svg:height="8cm"><draw:text-box>
    <text:p>Slide one: generated at fixture time.</text:p></draw:text-box></draw:frame>
  </draw:page>
  <draw:page draw:name="Slide 2" draw:master-page-name="Default">
   <draw:frame svg:x="2cm" svg:y="2cm" svg:width="24cm" svg:height="3cm"><draw:text-box>
    <text:p>Slide two</text:p></draw:text-box></draw:frame>
  </draw:page>
 </office:presentation></office:body>
</office:document>
"""

# A LibreOffice Basic macro that re-saves a document with a password (fixture time only).
ENCRYPT_MACRO = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script:module PUBLIC "-//OpenOffice.org//DTD OfficeDocument 1.0//EN" "module.dtd">
<script:module xmlns:script="http://openoffice.org/2000/script" script:name="Module1" script:language="StarBasic">
Sub Encrypt
  Dim la(0) As New com.sun.star.beans.PropertyValue
  la(0).Name = &quot;Hidden&quot; : la(0).Value = True
  Dim doc As Object
  doc = StarDesktop.loadComponentFromURL(ConvertToURL(Environ(&quot;BFX_SRC&quot;)), &quot;_blank&quot;, 0, la())
  Dim sa(1) As New com.sun.star.beans.PropertyValue
  sa(0).Name = &quot;FilterName&quot; : sa(0).Value = Environ(&quot;BFX_FILTER&quot;)
  sa(1).Name = &quot;Password&quot; : sa(1).Value = Environ(&quot;BFX_PASSWORD&quot;)
  doc.storeToURL(ConvertToURL(Environ(&quot;BFX_DST&quot;)), sa())
  doc.close(True)
  StarDesktop.terminate()
End Sub
</script:module>
"""


def html_doc(title: str) -> str:
    return HTML_DOC.format(title=title)


def _profile_args(tools) -> list[str]:  # noqa: ANN001
    return [tools.soffice, f"-env:UserInstallation={tools.profile_dir.resolve().as_uri()}", "--headless",
            "--invisible", "--nologo", "--norestore", "--nolockcheck", "--nodefault"]


def encrypt(tools, src: Path, export_filter: str, dst: Path, password: str = "baleen-test") -> Path:  # noqa: ANN001
    """Save `src` as `dst` with a password, through LibreOffice (fixture time)."""
    from baleen import proc

    tools.need("soffice")
    tools.profile_dir.mkdir(parents=True, exist_ok=True)
    module = tools.profile_dir / "user" / "basic" / "Standard" / "Module1.xba"
    if not module.exists() or "Sub Encrypt" not in module.read_text(encoding="utf-8", errors="replace"):
        proc.run([*_profile_args(tools), "--terminate_after_init"], timeout=180, env=tools.env)
        module.parent.mkdir(parents=True, exist_ok=True)
        module.write_text(ENCRYPT_MACRO, encoding="utf-8")
    env = dict(tools.env, BFX_SRC=str(src), BFX_FILTER=export_filter, BFX_DST=str(dst), BFX_PASSWORD=password)
    r = proc.run([*_profile_args(tools), "macro:///Standard.Module1.Encrypt"], timeout=180, env=env)
    if not dst.exists():
        raise RuntimeError(f"encrypting {src.name} failed: {r.err() or r.out()}")
    return dst


def damaged_ole(seed: int = 1, size: int = 6000) -> bytes:
    rnd = random.Random(seed)
    return b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + bytes(rnd.getrandbits(8) for _ in range(size))


def make_sources(tools, work: Path) -> dict[str, Path]:  # noqa: ANN001
    """Writer/Calc/Impress sources and their LibreOffice conversions, in `work`."""
    tools.need("soffice")
    work.mkdir(parents=True, exist_ok=True)
    out: dict[str, Path] = {}
    write_text(work / "report.html", html_doc("Annual report 2004"))
    write_text(work / "letter.html", html_doc("Letter to the archive"))
    write_text(work / "memo.html", html_doc("Memo"))
    write_text(work / "notes.html", html_doc("Interview notes"))
    write_text(work / "secret.html", html_doc("Confidential"))
    write_text(work / "budget.html", HTML_TABLE)
    write_text(work / "slides.fodp", FODP)
    out["report.doc"] = tools.soffice_convert(work / "report.html", "doc:MS Word 97", work)
    out["letter.docx"] = tools.soffice_convert(work / "letter.html", "docx:MS Word 2007 XML", work)
    out["memo.rtf"] = tools.soffice_convert(work / "memo.html", "rtf:Rich Text Format", work)
    out["notes.odt"] = tools.soffice_convert(work / "notes.html", "odt:writer8", work)
    out["secret.odt-src"] = tools.soffice_convert(work / "secret.html", "odt:writer8", work)
    out["budget.xls"] = tools.soffice_convert(work / "budget.html", "xls:MS Excel 97", work, infilter="HTML (StarCalc)")
    out["budget.ods"] = tools.soffice_convert(work / "budget.html", "ods:calc8", work, infilter="HTML (StarCalc)")
    out["slides.ppt"] = tools.soffice_convert(work / "slides.fodp", "ppt:MS PowerPoint 97", work)
    return out


def build(dest: Path, tools) -> None:  # noqa: ANN001
    tools.need("soffice")
    work = tools.profile_dir.parent / "documents-src"
    src = make_sources(tools, work)
    for name in ("report.doc", "letter.docx", "memo.rtf", "notes.odt", "budget.xls", "slides.ppt"):
        shutil.copyfile(src[name], dest / name)
    write_bytes(dest / "damaged.doc", damaged_ole())
    write_bytes(dest / "empty.doc", b"")
    encrypt(tools, src["secret.odt-src"], "MS Word 97", dest / "secret.doc")
    encrypt(tools, src["secret.odt-src"], "writer8", dest / "secret.odt")
    encrypt(tools, src["budget.ods"], "Calc MS Excel 2007 XML", dest / "secret.xlsx")
    encrypt(tools, src["budget.ods"], "MS Excel 97", dest / "velvet.xls", password="VelvetSweatshop")
    write_text(dest / "web-export.xls", HTML_TABLE)
    for p in dest.iterdir():
        os.utime(p, (1_100_000_000, 1_100_000_000))  # a fixed, plausible 2004 mtime
