"""Fixture group 'email' (spec §16.1). Owned by workstream (b): documents and e-mail.

Synthetic messages built with Python `email` (boundaries fixed, so the bytes are stable):

- plain.eml               plain UTF-8 (CJK subject and body, addresses, a mailto link)
- html_cid.eml            HTML body with a cid: image (multipart/related)
- report_and_photo.eml    two attachments: DOCX (generated by LibreOffice) + JPEG
- nested.eml              a forwarded message/rfc822 that carries a JPEG
- big5.eml                Big5 body and RFC 2047 Big5 subject, declared big5
- noname.eml              an attachment without a filename (application/rtf -> attachment-1.rtf)
- deep.eml                4-level nesting: level 4 -> EML_NESTING_TOO_DEEP
- tracking.eml            HTML with a remote tracking pixel and remote CSS (never fetched)
- R-07 cases: big5_undeclared.eml (no charset, raw 8-bit subject), big5_as_utf8.eml (declared
  utf-8), big5_as_latin1.eml (declared iso-8859-1: decodes without error, see STATUS R-07)
- garbage.eml             binary noise: not an e-mail -> CONVERSION_ERROR
"""

from __future__ import annotations

import base64
import os
import random
from email.message import EmailMessage
from email.policy import default as POLICY
from pathlib import Path

from .common import jpeg, rtf_text, write_bytes, write_text

DATE = "Mon, 02 Oct 2006 09:30:00 +0800"
BIG5_TEXT = "訪談記錄：二零零四年的展覽紀錄，共十二張照片。\n請於週五前回覆。\n"


def _boundaries(msg: EmailMessage, tag: str) -> EmailMessage:
    """Fixed MIME boundaries, so fixture bytes are identical on every build."""
    for i, part in enumerate(msg.walk()):
        if part.is_multipart() and part.get_content_maintype() == "multipart":
            part.set_boundary(f"=_baleen_{tag}_{i}")
    return msg


def _base(subject: str, frm: str = "Test Sender <sender@example.invalid>") -> EmailMessage:
    m = EmailMessage()
    m["From"] = frm
    m["To"] = "Archive <archive@example.invalid>"
    m["Cc"] = '"curator@example.invalid" <curator@example.invalid>'
    m["Date"] = DATE
    m["Subject"] = subject
    return m


def _jpeg_bytes(tmp: Path, name: str, color: tuple[int, int, int]) -> bytes:
    return jpeg(tmp / name, color=color).read_bytes()


def _save(dest: Path, name: str, msg: EmailMessage) -> None:
    write_bytes(dest / name, _boundaries(msg, name.split(".")[0]).as_bytes(policy=POLICY))


def plain() -> EmailMessage:
    m = _base("訪談 — interview schedule")
    m.set_content("Hello,\n\nThe interview is on Friday. Write to curator@example.invalid or reply to this\n"
                  "message. 訪談在星期五。\n\n" + "A long line that should wrap in the PDF. " * 8 + "\n")
    return m


def html_cid(photo: bytes) -> EmailMessage:
    m = _base("Newsletter with a logo")
    m.set_content("Plain-text alternative of the newsletter.")
    m.add_alternative('<html><body><h2>Newsletter</h2><p>Our logo:</p><img src="cid:logo@baleen.invalid" alt="logo">'
                      '<p>Contact <a href="mailto:news@example.invalid">news@example.invalid</a>.</p></body></html>',
                      subtype="html")
    m.get_payload()[1].add_related(photo, maintype="image", subtype="jpeg", cid="<logo@baleen.invalid>",
                                   filename="logo.jpg")
    return m


def report_and_photo(docx: bytes, photo: bytes) -> EmailMessage:
    m = _base("Report and photo")
    m.set_content("Attached: the report (DOCX) and a photo.")
    m.add_attachment(docx, maintype="application",
                     subtype="vnd.openxmlformats-officedocument.wordprocessingml.document", filename="report.docx")
    m.add_attachment(photo, maintype="image", subtype="jpeg", filename="photo.jpg")
    return m


def nested(photo: bytes) -> EmailMessage:
    inner = _base("Original message with a photo", frm="Photographer <photo@example.invalid>")
    inner.set_content("Here is the photo from the opening.")
    inner.add_attachment(photo, maintype="image", subtype="jpeg", filename="photo.jpg")
    _boundaries(inner, "nested_inner")
    m = _base("Fwd: Original message with a photo")
    m.set_content("Forwarding the message below.")
    m.add_attachment(inner, filename="fwd.eml")
    return m


def deep(photo: bytes) -> EmailMessage:
    level = _base("Level 4")
    level.set_content("The innermost message.")
    level.add_attachment(photo, maintype="image", subtype="jpeg", filename="photo.jpg")
    _boundaries(level, "deep4")
    for n in (3, 2):
        outer = _base(f"Level {n}")
        outer.set_content(f"Message at nesting level {n}.")
        outer.add_attachment(level, filename=f"level{n + 1}.eml")
        _boundaries(outer, f"deep{n}")
        level = outer
    m = _base("Level 1")
    m.set_content("The top-level message.")
    m.add_attachment(level, filename="level2.eml")
    return m


def noname() -> EmailMessage:
    m = _base("Attachment without a name")
    m.set_content("The attachment below has no filename.")
    m.add_attachment(rtf_text("Unnamed attachment"), maintype="application", subtype="rtf")
    att = m.get_payload()[1]
    del att["Content-Disposition"]
    att["Content-Disposition"] = "attachment"
    return m


def tracking() -> EmailMessage:
    m = _base("Special offer")
    m.set_content("Plain-text version.")
    m.add_alternative(
        '<html><head><style>body { background: url("https://cdn.example.invalid/bg.png"); }</style></head>'
        '<body><h1>Special offer</h1><p>Read more on our site.</p>'
        '<img src="http://tracker.example.invalid/open.gif?id=8f3a" width="1" height="1" alt="">'
        '<p><a href="https://example.invalid/offer">Offer page</a></p></body></html>', subtype="html")
    return m


def _raw(headers: list[tuple[str, bytes]], body: bytes, ctype: bytes) -> bytes:
    lines = [k.encode() + b": " + v for k, v in headers]
    lines += [b"MIME-Version: 1.0", b"Content-Type: " + ctype, b"Content-Transfer-Encoding: 8bit"]
    return b"\r\n".join(lines) + b"\r\n\r\n" + body.replace(b"\n", b"\r\n")


def big5_messages() -> dict[str, bytes]:
    body = BIG5_TEXT.encode("big5")
    common = [("From", b"Test Sender <sender@example.invalid>"), ("To", b"Archive <archive@example.invalid>"),
              ("Date", DATE.encode())]
    enc_subject = b"=?big5?B?" + base64.b64encode("訪談記錄".encode("big5")) + b"?="
    return {
        "big5.eml": _raw([*common, ("Subject", enc_subject)], body, b"text/plain; charset=big5"),
        "big5_undeclared.eml": _raw([*common, ("Subject", "訪談記錄".encode("big5"))], body, b"text/plain"),
        "big5_as_utf8.eml": _raw([*common, ("Subject", enc_subject)], body, b"text/plain; charset=utf-8"),
        "big5_as_latin1.eml": _raw([*common, ("Subject", enc_subject)], body, b"text/plain; charset=iso-8859-1"),
    }


def docx_bytes(tools, work: Path) -> bytes:  # noqa: ANN001
    from .documents import html_doc

    tools.need("soffice")
    work.mkdir(parents=True, exist_ok=True)
    write_text(work / "report.html", html_doc("Report attached to an e-mail"))
    return tools.soffice_convert(work / "report.html", "docx:MS Word 2007 XML", work).read_bytes()


def build(dest: Path, tools) -> None:  # noqa: ANN001
    work = tools.profile_dir.parent / "email-src"
    work.mkdir(parents=True, exist_ok=True)
    photo = _jpeg_bytes(work, "photo.jpg", (40, 90, 140))
    logo = _jpeg_bytes(work, "logo.jpg", (200, 40, 40))
    _save(dest, "plain.eml", plain())
    _save(dest, "html_cid.eml", html_cid(logo))
    _save(dest, "report_and_photo.eml", report_and_photo(docx_bytes(tools, work), photo))
    _save(dest, "nested.eml", nested(photo))
    _save(dest, "deep.eml", deep(photo))
    _save(dest, "noname.eml", noname())
    _save(dest, "tracking.eml", tracking())
    for name, data in big5_messages().items():
        write_bytes(dest / name, data)
    rnd = random.Random(3)
    write_bytes(dest / "garbage.eml", b"\x00\x01\x02\x03" + bytes(rnd.getrandbits(8) for _ in range(2000)))
    for p in dest.iterdir():
        os.utime(p, (1_160_000_000, 1_160_000_000))
