"""Fixture group 'pdf' (spec §16.1): plain PDF (NOT_PDFA); PDF/A-2b generated by LibreOffice;
encrypted PDF (PDF_ENCRYPTED). Plus a PDF whose XMP claims PDF/A-2b but isn't (PDFA_INVALID:
a claim alone never counts, DR-08). Synthetic only (pypdf, LibreOffice)."""

from __future__ import annotations

import io
import shutil
from pathlib import Path

from .common import write_bytes

PDFA_EXPORT = 'writer_pdf_Export:{"SelectPdfVersion":{"type":"long","value":"2"}}'

FAKE_XMP = """<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">
   <pdfaid:part>2</pdfaid:part>
   <pdfaid:conformance>B</pdfaid:conformance>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""


def _writer():  # noqa: ANN202
    from pypdf import PdfWriter

    w = PdfWriter()
    w.add_blank_page(width=300, height=200)
    w.add_metadata({"/Title": "Synthetic Baleen fixture", "/Producer": "Baleen fixtures (pypdf)"})
    return w


def _bytes(w) -> bytes:  # noqa: ANN001
    buf = io.BytesIO()
    w.write(buf)
    return buf.getvalue()


def build(dest: Path, tools) -> None:  # noqa: ANN001
    from pypdf.generic import DecodedStreamObject, NameObject

    write_bytes(dest / "plain.pdf", _bytes(_writer()))

    enc = _writer()
    enc.encrypt(user_password="synthetic", owner_password="synthetic-owner", algorithm="RC4-128")
    write_bytes(dest / "encrypted.pdf", _bytes(enc))

    fake = _writer()
    meta = DecodedStreamObject()
    meta.set_data(FAKE_XMP.encode("utf-8"))
    meta[NameObject("/Type")] = NameObject("/Metadata")
    meta[NameObject("/Subtype")] = NameObject("/XML")
    fake.root_object[NameObject("/Metadata")] = fake._add_object(meta)
    write_bytes(dest / "fake_claim.pdf", _bytes(fake))

    if tools.soffice:  # the PDF/A-2b row requires libreoffice; without it the file is simply absent
        work = tools.profile_dir.parent / "pdf-fixture"
        work.mkdir(parents=True, exist_ok=True)
        src = work / "pdfa2b.html"
        src.write_text("<html><body><h1>Synthetic PDF/A-2b</h1><p>Generated by LibreOffice for Baleen's "
                       "tests.</p></body></html>", encoding="utf-8")
        out = tools.soffice_convert(src, "pdf", work / "out", infilter="HTML (StarWriter)", export=PDFA_EXPORT)
        shutil.copyfile(out, dest / "pdfa2b.pdf")
