"""Build the vendored front-end assets (design handoff §12, spec §4, DR-03).

    python scripts/vendor_assets.py --cache DIR          # build and write the assets
    python scripts/vendor_assets.py --cache DIR --check  # rebuild in a temp folder, compare
    python scripts/vendor_assets.py --cache DIR --pin    # record registry integrity in assets.json

What it writes (all committed):

- src/baleen/static/htmx.min.js            htmx 2.x from the htmx.org npm tarball
- src/baleen/static/fonts/*.woff2          Inter 400/500/600, IBM Plex Mono 400/500, Cormorant
                                           Garamond 600, subset with pyftsubset (design §03)
- src/baleen/static/baleen.css             the prototype's <style> block minus the .gal rules
                                           (the Google Fonts link is not in it), plus the handoff
                                           @font-face block; the select chevron data: URI becomes
                                           select-chevron.svg because the CSP (SEC-6) has no
                                           data: image source
- src/baleen/static/select-chevron.svg     that chevron
- src/baleen/static/favicon.svg            the prototype's placeholder favicon (PLACEHOLDER)
- src/baleen/static/brand/walking-whale.png  the Walking Whale logo used in About (a Walking
                                           Whale trademark, not covered by Apache-2.0)
- src/baleen/templates/partials/icons.svg  the prototype's inline Lucide sprite
- THIRD_PARTY_NOTICES/assets/*             licence texts (0BSD, OFL-1.1, ISC)

npm tarballs are downloaded over HTTPS and verified against the sha512 integrity recorded in
scripts/assets.json and the registry metadata. Tarballs are unpacked with tarfile (no Node.js).
pyftsubset runs from an ephemeral `uv run --with fonttools --with brotli`, so fonttools is never
part of the project locks.
"""

from __future__ import annotations

import argparse
import base64
import filecmp
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PINS = ROOT / "scripts" / "assets.json"
PROTOTYPE = ROOT / "docs" / "prototype" / "baleen-prototype.html"
REGISTRY = "https://registry.npmjs.org"

# Prototype sprite id -> Lucide icon name (lucide-static icons/<name>.svg).
LUCIDE_NAMES: dict[str, tuple[str, ...]] = {
    "convert": ("arrow-right-left",),
    "check": ("list-checks",),
    "runs": ("history",),
    "tools": ("wrench",),
    "settings": ("settings",),
    "about": ("info",),
    "quit": ("power",),
    "menu": ("menu",),
    "collapse": ("panel-left-close",),
    "expand": ("panel-left-open",),
    "folder": ("folder",),
    "folder-open": ("folder-open",),
    "play": ("play",),
    "stop": ("square",),
    "close": ("x",),
    "download": ("download",),
    "external": ("external-link",),
    "copy": ("copy",),
    "search": ("search",),
    "chev-r": ("chevron-right",),
    "chev-d": ("chevron-down",),
    "chev-l": ("chevron-left",),
    "reset": ("rotate-ccw",),
    "spinner": ("loader-circle",),
    "tick": ("check",),
    "arrow-r": ("arrow-right",),
    "bell": ("bell",),
    "drive": ("hard-drive",),
    "shield": ("shield-check",),
    "more": ("ellipsis",),
    "clock": ("clock",),
    "filter": ("funnel", "filter"),
    "layers": ("layers",),
    "scan": ("scan-search",),
    "st-ok": ("circle-check",),
    "st-review": ("triangle-alert",),
    "st-failed": ("circle-x",),
    "st-unsupported": ("circle-question-mark", "circle-help"),
    "st-ignored": ("eye-off",),
    "st-skipped": ("circle-slash",),
    "st-unavail": ("circle-alert",),
    "cat-image": ("image",),
    "cat-document": ("file-text",),
    "cat-text": ("type",),
    "cat-html": ("code",),
    "cat-email": ("mail",),
    "cat-pdf": ("file",),
    "cat-video": ("film",),
    "cat-audio": ("music",),
    "cat-other": ("file-question-mark", "file-question"),
    "info": ("info",),
}

# The design handoff §12 @font-face block, line for line.
FONT_FACE = "/* fonts (replace the Google Fonts link) */\n" + "".join(
    f'@font-face{{font-family:"{family}";src:url("fonts/{file}-{w}.woff2") format("woff2");'
    f"font-weight:{w};font-display:swap}}\n"
    for family, file, w in (
        ("Inter", "Inter", 400), ("Inter", "Inter", 500), ("Inter", "Inter", 600),
        ("IBM Plex Mono", "IBMPlexMono", 400), ("IBM Plex Mono", "IBMPlexMono", 500),
        ("Cormorant Garamond", "CormorantGaramond", 600),
    )
)

CSS_HEADER = """/* baleen.css: design tokens + components (design doc v1.1, handoff §12).
   GENERATED by scripts/vendor_assets.py from docs/prototype/baleen-prototype.html; do not edit.
   Changes: .gal (gallery) rules dropped, @font-face block added, and the select chevron
   data: URI replaced by select-chevron.svg (the CSP of SEC-6 allows no data: images).
   App-only rules that replace the prototype's inline styles live in app.css. */
"""


# --------------------------------------------------------------------------- npm


def _get(url: str, timeout: float = 60) -> bytes:
    if not url.startswith("https://"):
        raise SystemExit(f"refusing a non-HTTPS URL: {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "baleen-vendor-assets"})
    with urllib.request.urlopen(req, timeout=timeout) as r:  # noqa: S310 - https only (checked)
        return r.read()


def registry_meta(name: str, version: str) -> dict:
    quoted = urllib.parse.quote(name, safe="@/")
    return json.loads(_get(f"{REGISTRY}/{quoted}/{version}"))


def sri_sha512(data: bytes) -> str:
    return "sha512-" + base64.b64encode(hashlib.sha512(data).digest()).decode()


def fetch_package(name: str, pin: dict, cache: Path) -> Path:
    """Download (or reuse) a verified tarball; return the unpacked package folder."""
    version = pin["version"]
    safe = name.replace("@", "").replace("/", "__")
    tgz = cache / f"{safe}-{version}.tgz"
    meta = registry_meta(name, version)
    reg_integrity = meta["dist"]["integrity"]
    url = meta["dist"]["tarball"]
    if not url.startswith(REGISTRY + "/"):
        raise SystemExit(f"{name}: unexpected tarball URL {url}")
    if pin.get("integrity") and pin["integrity"] != reg_integrity:
        raise SystemExit(f"{name}@{version}: registry integrity {reg_integrity} differs from the pin")
    expected = pin.get("integrity") or reg_integrity
    if tgz.exists() and sri_sha512(tgz.read_bytes()) != expected:
        tgz.unlink()
    if not tgz.exists():
        data = _get(url, timeout=300)
        if sri_sha512(data) != expected:
            raise SystemExit(f"{name}@{version}: tarball does not match its sha512 integrity")
        tgz.parent.mkdir(parents=True, exist_ok=True)
        tmp = tgz.with_suffix(".part")
        tmp.write_bytes(data)
        os.replace(tmp, tgz)
    dest = cache / "unpacked" / f"{safe}-{version}"
    if not (dest / "package" / "package.json").exists():
        if dest.exists():
            shutil.rmtree(dest)
        dest.mkdir(parents=True)
        with tarfile.open(tgz, "r:gz") as tf:
            tf.extractall(dest, filter="data")
    return dest / "package"


def pin_integrity(pins: dict) -> None:
    for name, pin in pins["npm"].items():
        meta = registry_meta(name, pin["version"])
        pin["integrity"] = meta["dist"]["integrity"]
        print(f"pinned {name}@{pin['version']} {pin['integrity'][:24]}…")
    PINS.write_text(json.dumps(pins, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------- prototype parts


def prototype_parts() -> dict[str, str]:
    html = PROTOTYPE.read_text(encoding="utf-8")
    style = re.search(r"<style>\n?(.*?)</style>", html, re.S)
    sprite = re.search(r'(<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">.*?</svg>)',
                       html, re.S)
    favicon = re.search(r'<link rel="icon" type="image/svg\+xml" href="data:image/svg\+xml;base64,([A-Za-z0-9+/=]+)">',
                        html)
    logo = re.search(r'var WW_LOGO="data:image/png;base64,([A-Za-z0-9+/=]+)"', html)
    if not (style and sprite and favicon and logo):
        raise SystemExit("prototype layout changed: style, sprite, favicon or logo not found")
    return {"style": style.group(1), "sprite": sprite.group(1), "favicon": favicon.group(1), "logo": logo.group(1)}


def build_css(style: str, out: Path) -> None:
    lines = style.splitlines()
    kept: list[str] = []
    for line in lines:
        s = line.strip()
        if s.startswith(".gal ") or s.startswith(".gal{") or s == "/* gallery (design reference route) */":
            continue
        kept.append(line)
    css = "\n".join(kept).strip("\n") + "\n"
    chevron = re.search(r'url\("data:image/svg\+xml,([^"]+)"\)', css)
    if not chevron:
        raise SystemExit("select chevron data: URI not found in the prototype CSS")
    svg = urllib.parse.unquote(chevron.group(1))
    (out / "select-chevron.svg").write_text(svg + "\n", encoding="utf-8", newline="\n")
    css = css.replace(chevron.group(0), 'url("select-chevron.svg")')
    if ".gal" in css or "data:" in css:
        raise SystemExit("baleen.css still contains gallery rules or a data: URI")
    (out / "baleen.css").write_text(CSS_HEADER + FONT_FACE + css, encoding="utf-8", newline="\n")


def build_sprite(sprite: str, out: Path) -> None:
    svg = sprite.replace('style="display:none"', 'class="sprite"', 1)
    header = ("<!-- Lucide icons (ISC licence, https://lucide.dev), the design prototype's sprite. "
              "GENERATED by scripts/vendor_assets.py. -->\n")
    out.write_text(header + svg + "\n", encoding="utf-8", newline="\n")


# --------------------------------------------------------------------------- lucide check


_ELEM = re.compile(r"<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)/?>")
_ATTR = re.compile(r'([a-zA-Z-]+)="([^"]*)"')


def _shape_set(svg_inner: str) -> list[tuple[str, tuple[tuple[str, str], ...]]]:
    shapes = []
    for tag, attrs in _ELEM.findall(svg_inner):
        a = tuple(sorted((k, v) for k, v in _ATTR.findall(attrs) if k not in ("class",)))
        shapes.append((tag, a))
    return sorted(shapes)


def check_lucide(sprite: str, lucide_pkg: Path) -> list[str]:
    report: list[str] = []
    for sid, inner in re.findall(r'<symbol id="i-([\w-]+)" viewBox="0 0 24 24">(.*?)</symbol>', sprite, re.S):
        names = LUCIDE_NAMES.get(sid)
        if not names:
            report.append(f"i-{sid}: no Lucide mapping")
            continue
        found = None
        for n in names:
            p = lucide_pkg / "icons" / f"{n}.svg"
            if p.exists():
                found = (n, p.read_text(encoding="utf-8"))
                break
        if not found:
            report.append(f"i-{sid}: lucide-static has no {' / '.join(names)}")
            continue
        n, text = found
        if _shape_set(inner) == _shape_set(text):
            report.append(f"i-{sid}: matches {n}")
        else:
            report.append(f"i-{sid}: DIFFERS from {n} (prototype kept)")
    return report


# --------------------------------------------------------------------------- fonts


def subset_fonts(pins: dict, pkgs: dict[str, Path], out: Path) -> None:
    """Subset each face to the design §03 ranges. Fontsource's `latin` file is the source; no
    fontsource subset carries the → arrow (U+2192), so that glyph falls back to the system font."""
    out.mkdir(parents=True, exist_ok=True)
    tool = pins["pyftsubset"]
    base = ["uv", "run", "--no-project", "--quiet", "--with", f"fonttools=={tool['fonttools']}",
            "--with", f"brotli=={tool['brotli']}"]
    for spec in pins["fonts"]:
        src = pkgs[spec["package"]] / "files" / f"{spec['family']}-{pins['font_subset']}-{spec['weight']}-normal.woff2"
        if not src.exists():
            raise SystemExit(f"no source font for {spec}")
        dest = out / spec["out"]
        subprocess.run([
            *base, "pyftsubset", str(src), f"--unicodes={pins['unicodes']}", "--flavor=woff2",
            f"--layout-features={pins['layout_features']}", "--name-IDs=*", "--name-languages=*",
            "--no-hinting", "--desubroutinize", f"--output-file={dest}",
        ], check=True)
        print(f"font {spec['out']}: {dest.stat().st_size / 1024:.1f} KB")


# --------------------------------------------------------------------------- build


def build(pins: dict, cache: Path, root: Path) -> list[str]:
    static = root / "src" / "baleen" / "static"
    templates = root / "src" / "baleen" / "templates"
    notices = root / "THIRD_PARTY_NOTICES" / "assets"
    for d in (static, static / "fonts", static / "brand", templates / "partials", notices):
        d.mkdir(parents=True, exist_ok=True)
    pkgs = {name: fetch_package(name, pin, cache) for name, pin in pins["npm"].items()}

    shutil.copyfile(pkgs["htmx.org"] / "dist" / "htmx.min.js", static / "htmx.min.js")

    parts = prototype_parts()
    build_css(parts["style"], static)
    build_sprite(parts["sprite"], templates / "partials" / "icons.svg")
    fav = base64.b64decode(parts["favicon"]).decode("utf-8")
    if "PLACEHOLDER" not in fav:
        raise SystemExit("prototype favicon lost its PLACEHOLDER marker")
    (static / "favicon.svg").write_text(fav + "\n", encoding="utf-8", newline="\n")
    (static / "brand" / "walking-whale.png").write_bytes(base64.b64decode(parts["logo"]))

    subset_fonts(pins, pkgs, static / "fonts")

    licences = {
        "htmx.org": "htmx-0BSD.txt",
        "@fontsource/inter": "Inter-OFL.txt",
        "@fontsource/ibm-plex-mono": "IBMPlexMono-OFL.txt",
        "@fontsource/cormorant-garamond": "CormorantGaramond-OFL.txt",
        "lucide-static": "Lucide-ISC.txt",
    }
    for name, fname in licences.items():
        src = next((p for p in (pkgs[name] / "LICENSE", pkgs[name] / "LICENSE.md", pkgs[name] / "LICENSE.txt")
                    if p.exists()), None)
        if src is None:
            raise SystemExit(f"{name}: no licence file in the package")
        head = f"{name} {pins['npm'][name]['version']} ({pins['npm'][name]['license']})\n\n"
        (notices / fname).write_text(head + src.read_text(encoding="utf-8").replace("\r\n", "\n"),
                                     encoding="utf-8", newline="\n")
    return check_lucide(parts["sprite"], pkgs["lucide-static"])


OUTPUTS = (
    "src/baleen/static/htmx.min.js",
    "src/baleen/static/baleen.css",
    "src/baleen/static/select-chevron.svg",
    "src/baleen/static/favicon.svg",
    "src/baleen/static/brand/walking-whale.png",
    "src/baleen/templates/partials/icons.svg",
    "THIRD_PARTY_NOTICES/assets/htmx-0BSD.txt",
    "THIRD_PARTY_NOTICES/assets/Inter-OFL.txt",
    "THIRD_PARTY_NOTICES/assets/IBMPlexMono-OFL.txt",
    "THIRD_PARTY_NOTICES/assets/CormorantGaramond-OFL.txt",
    "THIRD_PARTY_NOTICES/assets/Lucide-ISC.txt",
)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--cache", type=Path, default=ROOT / ".scratch" / "assets-cache",
                    help="download and unpack folder (default: .scratch/assets-cache)")
    ap.add_argument("--check", action="store_true", help="rebuild in a temp folder and compare with the repo")
    ap.add_argument("--pin", action="store_true", help="record the registry integrity of every pinned package")
    ns = ap.parse_args(argv)
    pins = json.loads(PINS.read_text(encoding="utf-8"))
    ns.cache.mkdir(parents=True, exist_ok=True)
    if ns.pin:
        pin_integrity(pins)
        return 0
    if any(not p.get("integrity") for p in pins["npm"].values()):
        raise SystemExit("assets.json has packages without an integrity pin; run with --pin first")
    if ns.check:
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            build(pins, ns.cache, tmp)
            bad = [rel for rel in OUTPUTS if not filecmp.cmp(tmp / rel, ROOT / rel, shallow=False)]
            fonts = sorted(p.name for p in (tmp / "src/baleen/static/fonts").glob("*.woff2"))
            bad += [f"fonts/{f}" for f in fonts
                    if not filecmp.cmp(tmp / "src/baleen/static/fonts" / f, ROOT / "src/baleen/static/fonts" / f,
                                       shallow=False)]
        if bad:
            print("out of date:", *bad, sep="\n  ")
            return 1
        print("all vendored assets are up to date")
        return 0
    for line in build(pins, ns.cache, ROOT):
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
