"""Generate every test input (spec §16.1). Synthetic only: no real archive data, ever.

    python tests/fixtures/make_fixtures.py DEST [--groups images,media,...] [--smoke]

Each group writes into DEST/<group>/ and is converted as its own source root by the golden
integration test (tests/integration/test_golden.py, expected.csv). Group modules live in
tests/fixtures/groups/<group>.py and define `build(dest: Path, tools: FixtureTools) -> None`.
Generators may use Pillow, pypdf, Python `email`, and the bundled LibreOffice and FFmpeg
(through FixtureTools). A group that needs a missing tool raises ToolUnavailable.
"""

from __future__ import annotations

import argparse
import importlib
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

GROUPS = ("images", "text", "html", "pdf", "documents", "email", "media", "other", "names")


class ToolUnavailable(Exception):
    pass


@dataclass
class FixtureTools:
    """Paths to the external tools a generator may use (bundled runtime first, like Baleen)."""

    soffice: str | None
    ffmpeg: str | None
    ffprobe: str | None
    env: dict[str, str]
    profile_dir: Path  # private LibreOffice profile for fixture generation

    @classmethod
    def detect(cls, work: Path) -> FixtureTools:
        from baleen.home import Home
        from baleen.tools import Toolset

        home = Home(work / "fixture-home")
        home.ensure()
        ts = Toolset(home)
        # Fixture inputs may need encoders Baleen itself never uses (e.g. LAME for the MP3 fixture);
        # BALEEN_FIXTURE_FFMPEG selects a full FFmpeg for generating them only.
        ffmpeg = os.environ.get("BALEEN_FIXTURE_FFMPEG") or ts.path("ffmpeg")
        return cls(ts.path("libreoffice"), ffmpeg, ts.path("ffprobe"), ts.env(), work / "lo-profile")

    def need(self, *names: str) -> None:
        for n in names:
            if getattr(self, n) is None:
                raise ToolUnavailable(n)

    def soffice_convert(self, src: Path, target: str, outdir: Path, infilter: str | None = None,
                        export: str | None = None) -> Path:
        """Fixture-time document generation, e.g. HTML -> .doc (spec §16.1 'generated by LibreOffice')."""
        from baleen import proc

        self.need("soffice")
        self.profile_dir.mkdir(parents=True, exist_ok=True)
        outdir.mkdir(parents=True, exist_ok=True)
        conv = f"{target}:{export}" if export else target
        args = [self.soffice, f"-env:UserInstallation={self.profile_dir.resolve().as_uri()}", "--headless",
                "--invisible", "--nologo", "--norestore", "--nolockcheck", "--nodefault"]
        if infilter:
            args.append(f"--infilter={infilter}")
        args += ["--convert-to", conv, "--outdir", str(outdir), str(src)]
        r = proc.run(args, timeout=180, env=self.env)
        out = outdir / (src.stem + "." + target.split(":")[0])
        if not out.exists():
            raise RuntimeError(f"soffice failed for {src.name}: {r.err() or r.out()}")
        return out

    def ffmpeg_run(self, args: list[str], timeout: float = 180) -> None:
        from baleen import proc

        self.need("ffmpeg")
        r = proc.run([self.ffmpeg, "-hide_banner", "-loglevel", "error", "-nostdin", "-y", *args],
                     timeout=timeout, env=self.env)
        if not r.ok:
            raise RuntimeError(f"ffmpeg failed: {' '.join(args)}\n{r.err()}")


def build(dest: Path, groups: list[str] | None = None, *, clean: bool = True) -> dict[str, str]:
    """Build the requested groups. Returns {group: "ok" | "skipped: <tool>" | "missing"}."""
    dest.mkdir(parents=True, exist_ok=True)
    tools = FixtureTools.detect(dest / ".work")
    status: dict[str, str] = {}
    for g in groups or list(GROUPS):
        target = dest / g
        if clean and target.exists():
            shutil.rmtree(target)
        try:
            mod = importlib.import_module(f"tests.fixtures.groups.{g}")
        except ModuleNotFoundError:
            status[g] = "missing"
            continue
        target.mkdir(parents=True, exist_ok=True)
        try:
            mod.build(target, tools)
            status[g] = "ok"
        except ToolUnavailable as e:
            shutil.rmtree(target, ignore_errors=True)
            status[g] = f"skipped: {e}"
        except NotImplementedError:
            shutil.rmtree(target, ignore_errors=True)
            status[g] = "not built yet"
    shutil.rmtree(dest / ".work", ignore_errors=True)
    return status


def build_smoke(dest: Path) -> None:
    from tests.fixtures.groups import smoke

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    smoke.build(dest, FixtureTools.detect(dest.parent / f".{dest.name}-work"))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("dest")
    ap.add_argument("--groups", default="")
    ap.add_argument("--smoke", action="store_true", help="build only the small smoke set (bundle smoke test)")
    ns = ap.parse_args(argv)
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    dest = Path(os.path.abspath(ns.dest))
    if ns.smoke:
        build_smoke(dest)
        print(f"smoke fixtures in {dest}")
        return 0
    status = build(dest, [g for g in ns.groups.split(",") if g] or None)
    for g, s in status.items():
        print(f"{g:10} {s}")
    return 0


if __name__ == "__main__":
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    sys.exit(main())
